Mobile menu date 12/21/2022
fithamlak/My-Portfolio pull request #11
Opened 2022-12-21 09:00 UTC by fithamlak

=>I  implement all the following features:
  -When the user clicks (or taps) the hamburger button, the mobile menu appears.
 -When the user clicks (or taps) the close (X) button, the mobile menu disappears.
 -When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
 -When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.

I was also on coding partner challenge 

![image](https://user-images.githubusercontent.com/49729863/208863221-20504599-cb4b-4ac1-84e5-757b0521ab7d.png)

2022-12-21 09:11 UTC, mirouhml commented
Hi @fithamlak, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a complete README, please know that all main headers from the [README template](https://github.com/microverseinc/readme-template) should be present, the only optional section is FAQ, also, make sure to add the section Future Features, including 1-3 potential features to be added.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-12-21 09:51 UTC, mckent05 requested changes
Hi @fithamlak, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- Good job using the correct workflow for this milestone 👏 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-21 09:51 UTC, mckent05 commented on index.html
>                  <a href="#footer-header">Contact</a>
- Good job done so far 👏, but there are some differences between your project and the Figma template. Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏.

Your project:
-- **OPTIONAL** - Please ensure your logo is centered in the middle of the navbar to help improve the UI of your website 👍 👍 
<img width="148" alt="bjejaet" src="https://user-images.githubusercontent.com/73607512/208875495-1d7f5052-89b5-448d-9cb1-6878e06b02d5.PNG">

-- You have not styled the mobile menu the way it is in the design template, please remember to stick to the styles in the design (fonts, color, bg images, margins, et.c..). Please style your mobile menu so it looks close to the one in the Figma template 🙏 
<img width="153" alt="egwrgwrg" src="https://user-images.githubusercontent.com/73607512/208875423-46c61882-22e6-4273-9fcd-fb53305ec80a.PNG">

Figma Design:
<img width="145" alt="bqehfbqhe" src="https://user-images.githubusercontent.com/73607512/208875456-bd25b148-2c6b-4ebb-a9f3-36655f989d54.PNG">

2022-12-21 12:13 UTC, uwadonat approved these changes
## Hi @fithamlak,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- No linter errors ✔️
- Clean and well organized project ✔️
![awoseme](https://user-images.githubusercontent.com/65860678/208902143-04a1aba4-7ed8-4ee7-a13d-6e2c1f39fc24.gif)


# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-12-21 12:18 UTC, merged

2022-12-21 12:18 UTC, fithamlak commented
mobile menu pop up is done, thank you for your constructive feedback.

2023-01-03 17:24 UTC, Abenezer-Tilahun reviewed
Hi @fithamlak 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Github-Flow.
✔️ Professional README  
✔️ Good Commit Messages
✔️ Good job for Implemented Portfolio - mobile menu

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._