Preserve data in the browser date 12/23/2022
fithamlak/My-Portfolio pull request #13
Opened 2022-12-23 10:12 UTC by fithamlak

=>Implement all requirements for Preserve data in the browser project and all passed like
  -  get form elements and check local storage
  - create a single object for contact data and listen to change on input fields
  - finally stringify that dat
![coding-partner-challenge](https://user-images.githubusercontent.com/49729863/209317307-169e3fa0-2f30-4c06-b59a-95c8774240b6.PNG)
a and set the object to local on loads of page

2022-12-23 10:42 UTC, Tadesse-Alemayehu requested changes
### Hi @fithamlak 
### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![EquatorialVictoriousBlackpanther-size_restricted](https://user-images.githubusercontent.com/69077061/204090500-5512fd84-cfd9-4aee-9d5d-8ee90740a92d.gif)

## Highlights
 - [ ]  Correct GitHub Flow  ✅
 - [ ]  Good commit history  ✅
 - [ ]  Good PR title/description  ✅ 
## Required Changes ♻️
- [ ] Dear @fithamlak, As part of this milestone we need to have the JavaScript linter `Eslint` Please add the JavaScript linter to your project.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-23 10:42 UTC, Tadesse-Alemayehu commented on index.js
> +}
Dear @fithamlak, Good job so far, As part of the main requirement for this project we should be able to store and retrieve data from local storage. Your form is saving the data only once and only if hit submit. on the next reload the content are not available. Please address this for a better user experience. 
### Remember the following point as you work on the contact form. 

- [ ] The contact form information is persistent to page reloads, This includes after filling the form and not submitting it.
- [ ] When visiting the page the form inputs should be contained, be auto-populated with, the values entered in the previous visit to the page. and If at the previous visit to the page, in the same browser, no input was entered in the form then the form inputs should remain empty.
- [ ] To achieve both features that I have mentioned you could make use of `localStorage.getItem` and `localStorage.setItem`

2022-12-23 12:27 UTC, Olamarx requested changes
Hi @fithamlak, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media3.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

 ## Highlights
- Linters passed ✔️
- Readme file ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-23 12:27 UTC, Olamarx commented on index.js
> +    nameInput.value = name || '';
- [ ] As the previous reviewer observed, the data is not getting and I also found out that it is also not saved in the localStorage. I tried to check your code further, but I could not find where you declared `nameInput` I see that you added eventLister to it on line 106 and my console has an error with it.
Kindly dig further into the tag you are adding to the event listener.
### The console error
![image](https://user-images.githubusercontent.com/86200356/209335864-f3409cfa-c6c4-4abd-b364-1333c5ab3ab8.png)

2022-12-23 13:14 UTC, KayLemba approved these changes
[# STATUS: APPROVED :green_circle: :clap: 

Hello  @fithamlak        , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- [x]  Your repo is professional 
- [x] Descriptive P.R
- [x] Descriptive README file




 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]

2022-12-23 15:14 UTC, merged

2023-01-06 19:39 UTC, huseyinbiyik commented
Hi @fithamlak,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Alt Text](https://media.giphy.com/media/xUPGcwE3CUkXlvonug/giphy.gif)

## Invalid Code Review Request

❗️ You have submitted a project, that has a missing section in your Readme. Please make sure you added the section Future Features, including 1-3 potential features to be added. Please notice that even though it is approved I need to check everything like it is the first review. 


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._